"""Builds Site/maries-story.html from the approved story, word for word.

Run from the repository root:  python3 Site/tools/build_story.py
Source: MVP/Stories/Maries_Story.md (the approved version). The page shows the
story from Chapter 1 to the Founders' Reflection; the document's metadata block
is left out. Nothing is reworded: only Markdown marks become HTML.
"""
import html
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
SOURCE = ROOT / "MVP" / "Stories" / "Maries_Story.md"
TARGET = ROOT / "Site" / "maries-story.html"


def inline(text: str) -> str:
    text = html.escape(text, quote=False)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"\*(.+?)\*", r"<em>\1</em>", text)
    return text


def build() -> None:
    raw = SOURCE.read_text(encoding="utf-8")
    version = re.search(r"\*\*Version:\*\*\s*([\d.]+)", raw).group(1)
    body = raw[raw.index("# **Chapter 1"):]
    blocks = [b.strip() for b in re.split(r"\n\s*\n", body) if b.strip()]

    out = []
    in_card = False
    i = 0
    while i < len(blocks):
        block = blocks[i]
        if block == "---":
            # The story shows the app's opening screen between two rules.
            nxt = blocks[i + 1] if i + 1 < len(blocks) else ""
            if not in_card and nxt.startswith("**Ask Pip**"):
                out.append('<div class="app-card">')
                in_card = True
            elif in_card:
                out.append("</div>")
                in_card = False
            else:
                out.append("<hr />")
        elif block.startswith("#"):
            title = block.lstrip("#").strip().strip("*").strip()
            out.append(f"<h2>{html.escape(title, quote=False)}</h2>")
        elif block.startswith("- "):
            items = "".join(f"<li>{inline(line[2:].strip())}</li>" for line in block.splitlines())
            out.append(f"<ul>{items}</ul>")
        elif block.startswith('"This story reminds'):
            out.append(f"<blockquote><p>{inline(block)}</p></blockquote>")
        else:
            out.append(f"<p>{inline(' '.join(block.splitlines()))}</p>")
        i += 1

    story = "\n        ".join(out)
    page = f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Marie's Story — Ask Pip</title>
    <meta name="description" content="Marie's first guided-care journey with Sarah's Rose: the story behind Ask Pip." />
    <meta name="theme-color" content="#f3f5f0" />
    <link rel="icon" type="image/png" href="assets/favicon.png" />
    <link rel="stylesheet" href="styles.css" />
  </head>
  <body>
    <!-- Generated by Site/tools/build_story.py from MVP/Stories/Maries_Story.md (Version {version}, approved).
         Do not edit this file by hand: change the approved story, then run the tool again. -->
    <header class="top">
      <div class="wrap top-row">
        <a class="brand" href="index.html" aria-label="Ask Pip, home">
          <img src="assets/logo-96.webp" width="44" height="44" alt="" />
          <span>Ask Pip</span>
        </a>
        <a class="btn btn-petal btn-small" href="index.html#join">Join the beta</a>
      </div>
    </header>
    <main class="story-page">
      <div class="wrap">
        <h1>Marie's Story</h1>
        <p class="subtitle">Ask Pip's Purpose</p>
        {story}
        <p style="margin-top: 2.5em"><a class="link" href="index.html">Back to Ask Pip</a></p>
      </div>
    </main>
    <footer class="foot">
      <div class="wrap foot-row">
        <img src="assets/pip-front.webp" width="600" height="460" loading="lazy" alt="" />
        <p class="foot-tag">Growing Understanding, Cultivating Confidence</p>
        <nav class="foot-links" aria-label="Footer">
          <a href="index.html#beta">About this beta</a>
          <a href="privacy.html">Privacy</a>
          <a href="terms.html">Terms</a>
          <a href="mailto:founders@askpip.garden">founders@askpip.garden</a>
        </nav>
        <p class="foot-copy">© 2026 AskPIP</p>
      </div>
    </footer>
  </body>
</html>
"""
    TARGET.write_text(page, encoding="utf-8")
    print(f"Wrote {TARGET.relative_to(ROOT)} from the story, Version {version}.")


if __name__ == "__main__":
    build()
